// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnXsuwdU8nSxORDHlUK811W5OjkXhYDEk',
    appId: '1:35605937195:web:fc53ba3ca3d5a2b8a17e6e',
    messagingSenderId: '35605937195',
    projectId: 'api-project-35605937195',
    authDomain: 'api-project-35605937195.firebaseapp.com',
    databaseURL: 'https://api-project-35605937195.firebaseio.com',
    storageBucket: 'api-project-35605937195.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUuzPOmz3zV14GRxUb7ki13jr3Rfg_8I0',
    appId: '1:35605937195:android:5f4c2c27c289cab2a17e6e',
    messagingSenderId: '35605937195',
    projectId: 'api-project-35605937195',
    databaseURL: 'https://api-project-35605937195.firebaseio.com',
    storageBucket: 'api-project-35605937195.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDFbhtA-m3Is17dXcRdIqqsO0jPMa653g',
    appId: '1:35605937195:ios:ee29bcf39426c676a17e6e',
    messagingSenderId: '35605937195',
    projectId: 'api-project-35605937195',
    databaseURL: 'https://api-project-35605937195.firebaseio.com',
    storageBucket: 'api-project-35605937195.appspot.com',
    iosBundleId: 'com.example.uberRiderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDFbhtA-m3Is17dXcRdIqqsO0jPMa653g',
    appId: '1:35605937195:ios:de4e95eca57ba6f2a17e6e',
    messagingSenderId: '35605937195',
    projectId: 'api-project-35605937195',
    databaseURL: 'https://api-project-35605937195.firebaseio.com',
    storageBucket: 'api-project-35605937195.appspot.com',
    iosBundleId: 'com.example.uberRiderApp.RunnerTests',
  );
}
